# Generated by Django 2.1.2 on 2018-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20181020_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='points',
            field=models.CharField(max_length=50, null=True, verbose_name='教学特点'),
        ),
    ]
