# Generated by Django 2.1.2 on 2018-10-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20181024_1727'),
        ('organization', '0005_auto_20181022_2250'),
    ]

    operations = [
    ]
