# Generated by Django 2.1.2 on 2018-10-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181022_2250'),
        ('courses', '0002_auto_20181023_1556'),
    ]

    operations = [
    ]
